language: node_js
node_js:
  - "12"
install:
  - "npm install"
jobs:
  include:
    - stage: build
      script: npm run build
    - stage: test
      script: npm test
    - stage: dry-run
      if: type IN (pull_request)
      script: npm publish --dry-run
    - stage: deploy
      if: NOT type IN (pull_request)
      script: npm publish --access=public